In [1]:
print("hello world")

hello world

In [9]:
import os
from pathlib import Path
from IPython.display import display
os.getcwd()
os.chdir(r"C:\Users\pari1\Desktop\TSU\Engineering\Census Data\csv")
os.getcwd()
import pandas as pd
folder = Path(r"C:\Users\pari1\Desktop\TSU\Engineering\Census Data\csv")  # <-- your folder

for csv_path in folder.glob("*.csv"):
    print("Processing:", csv_path.name)

    df = pd.read_csv(csv_path)

Processing: departure.csv
Processing: Educational_attainment.csv
Processing: employment.csv
Processing: gender.csv
Processing: householdsize.csv
Processing: means of transportation.csv
Processing: median_household_income.csv
Processing: poverty_status.csv
Processing: race.csv
Processing: total_population.csv
Processing: travel_time.csv
Processing: units.csv
Processing: vehicle_availability.csv
Processing: workers_industry.csv

In [25]:
for csv_path in folder.glob("*.csv"):
    print("\n==============================")
    print("File:", csv_path.name)
    print("==============================")

    df = pd.read_csv(csv_path)

    # show first few rows (change 5 to any number you like)
    # display(df.head(5))

    #  # read whole CSV as text
    # txt = csv_path.read_text(encoding="utf-8")

    # # replace the phrase
    # # 👉 option A: remove it completely
    # # txt = txt.replace("!!", "")

    # # 👉 if you prefer literal "None" instead, use this instead:
    # # txt = txt.replace("Estimate!! Margin of Error!!", "None")

    # # write back to the same file
    # csv_path.write_text(txt, encoding="utf-8")

==============================
File: departure.csv
==============================

==============================
File: Educational_attainment.csv
==============================

==============================
File: employment.csv
==============================

==============================
File: gender.csv
==============================

==============================
File: householdsize.csv
==============================

==============================
File: means of transportation.csv
==============================

==============================
File: median_household_income.csv
==============================

==============================
File: poverty_status.csv
==============================

==============================
File: race.csv
==============================

==============================
File: total_population.csv
==============================

==============================
File: travel_time.csv
==============================

==============================
File: units.csv
==============================

==============================
File: vehicle_availability.csv
==============================

==============================
File: workers_industry.csv
==============================

In [23]:
import pandas as pd

path = r"C:\Users\pari1\Desktop\TSU\Engineering\Census Data\csv\departure.csv"

df = pd.read_csv(path)

# Split NAME
parts = df["NAME"].astype(str).str.split(";", n=2, expand=True)

df["Area"]   = parts[0].str.strip()
df["County"] = parts[1].str.strip()
df["State"]  = parts[2].str.strip()

# Only show relevant columns to verify
print(df[["NAME", "Area", "County", "State"]].head(10))

                                              NAME                  Area  \
0                             Geographic Area Name  Geographic Area Name
1                                        Tennessee             Tennessee
2     Census Tract 201; Anderson County; Tennessee      Census Tract 201
3  Census Tract 202.01; Anderson County; Tennessee   Census Tract 202.01
4  Census Tract 202.02; Anderson County; Tennessee   Census Tract 202.02
5     Census Tract 203; Anderson County; Tennessee      Census Tract 203
6     Census Tract 204; Anderson County; Tennessee      Census Tract 204
7     Census Tract 205; Anderson County; Tennessee      Census Tract 205
8     Census Tract 206; Anderson County; Tennessee      Census Tract 206
9     Census Tract 207; Anderson County; Tennessee      Census Tract 207

            County      State
0             None       None
1             None       None
2  Anderson County  Tennessee
3  Anderson County  Tennessee
4  Anderson County  Tennessee
5  Anderson County  Tennessee
6  Anderson County  Tennessee
7  Anderson County  Tennessee
8  Anderson County  Tennessee
9  Anderson County  Tennessee

In [26]:
from pathlib import Path
import pandas as pd
from IPython.display import display

folder = Path(r"C:\Users\pari1\Desktop\TSU\Engineering\Census Data\csv")

for csv_path in folder.glob("*.csv"):
    print("\n==============================")
    print("File:", csv_path.name)
    print("==============================")

    df = pd.read_csv(csv_path)

    if "NAME" in df.columns:
        parts = df["NAME"].astype(str).str.split(";", n=2, expand=True)

        df["Area"]   = parts[0].str.strip()
        df["County"] = parts[1].str.strip()
        df["State"]  = parts[2].str.strip()

        # show just the important columns to check
        display(df[["NAME", "Area", "County", "State"]].head())
    else:
        print("  -> WARNING: 'NAME' column not found in this file")

    # save back (overwrite)
    df.to_csv(csv_path, index=False)

==============================
File: departure.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: Educational_attainment.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: employment.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: gender.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: householdsize.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: means of transportation.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: median_household_income.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: poverty_status.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: race.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: total_population.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: travel_time.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: units.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: vehicle_availability.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

==============================
File: workers_industry.csv
==============================

,NAME,Area,County,State
0,Geographic Area Name,Geographic Area Name,None,None
1,Tennessee,Tennessee,None,None
2,Census Tract 201; Anderson County; Tennessee,Census Tract 201,Anderson County,Tennessee
3,Census Tract 202.01; Anderson County; Tennessee,Census Tract 202.01,Anderson County,Tennessee
4,Census Tract 202.02; Anderson County; Tennessee,Census Tract 202.02,Anderson County,Tennessee

In [28]:
from pathlib import Path
import pandas as pd
from IPython.display import display

folder = Path(r"C:\Users\pari1\Desktop\TSU\Engineering\Census Data\csv")

for csv_path in folder.glob("*.csv"):
    print("\n==============================")
    print("File:", csv_path.name)
    print("==============================")

    df = pd.read_csv(csv_path)

    if "NAME" in df.columns:
        # --- split NAME into 3 columns ---
        parts = df["NAME"].astype(str).str.split(";", n=2, expand=True)
        df["Area"]   = parts[0].str.strip()
        df["County"] = parts[1].str.strip()
        df["State"]  = parts[2].str.strip()

        # --- drop NAME column ---
        df = df.drop(columns=["NAME"])

        # --- move Area/County/State to the beginning ---
        cols = df.columns.tolist()
        first = ["Area", "County", "State"]
        rest = [c for c in cols if c not in first]
        df = df[first + rest]

        # quick check
        display(df.head())
    else:
        print("  -> WARNING: 'NAME' column not found in this file")

    # save back (overwrite)
    df.to_csv(csv_path, index=False)

==============================
File: departure.csv
==============================

,Area,County,State,GEO_ID,B08302_001E,B08302_001M,B08302_002E,B08302_002M,B08302_003E,B08302_003M,...,B08302_011M,B08302_012E,B08302_012M,B08302_013E,B08302_013M,B08302_014E,B08302_014M,B08302_015E,B08302_015M,Unnamed: 32
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:12:00 a.m. to 4:59 a.m.,Total:12:00 a.m. to 4:59 a.m.,Total:5:00 a.m. to 5:29 a.m.,Total:5:00 a.m. to 5:29 a.m.,...,Total:9:00 a.m. to 9:59 a.m.,Total:10:00 a.m. to 10:59 a.m.,Total:10:00 a.m. to 10:59 a.m.,Total:11:00 a.m. to 11:59 a.m.,Total:11:00 a.m. to 11:59 a.m.,Total:12:00 p.m. to 3:59 p.m.,Total:12:00 p.m. to 3:59 p.m.,Total:4:00 p.m. to 11:59 p.m.,Total:4:00 p.m. to 11:59 p.m.,NaN
1,Tennessee,None,None,0400000US47,2885193,9455,162047,3476,125368,3116,...,3515,73708,2350,35146,1904,196111,4401,216805,4000,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,1219,282,203,185,0,14,...,80,80,55,18,27,109,95,152,78,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,1967,243,65,45,169,119,...,81,34,37,57,53,88,46,30,25,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,1501,413,72,71,26,48,...,47,20,33,70,66,165,114,113,91,NaN

==============================
File: Educational_attainment.csv
==============================

,Area,County,State,GEO_ID,B15003_001E,B15003_001M,B15003_002E,B15003_002M,B15003_003E,B15003_003M,...,B15003_021M,B15003_022E,B15003_022M,B15003_023E,B15003_023M,B15003_024E,B15003_024M,B15003_025E,B15003_025M,Unnamed: 52
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:No schooling completed,Total:No schooling completed,Total:Nursery school,Total:Nursery school,...,Total:Associate's degree,Total:Bachelor's degree,Total:Bachelor's degree,Total:Master's degree,Total:Master's degree,Total:Professional school degree,Total:Professional school degree,Total:Doctorate degree,Total:Doctorate degree,NaN
1,Tennessee,None,None,0400000US47,4805533,1359,60910,2397,1092,255,...,5481,913559,9360,386013,5745,90905,3041,70024,2289,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,2011,307,62,42,0,14,...,97,439,139,134,66,8,13,22,18,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,3647,357,8,11,0,19,...,72,906,176,732,184,63,38,407,127,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,3217,443,9,18,0,14,...,76,572,178,212,93,61,54,170,135,NaN

==============================
File: employment.csv
==============================

,Area,County,State,GEO_ID,B23025_001E,B23025_001M,B23025_002E,B23025_002M,B23025_003E,B23025_003M,B23025_004E,B23025_004M,B23025_005E,B23025_005M,B23025_006E,B23025_006M,B23025_007E,B23025_007M,Unnamed: 16
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:In labor force:,Total:In labor force:,Total:In labor force:Civilian labor force:,Total:In labor force:Civilian labor force:,Total:In labor force:Civilian labor force:Empl...,Total:In labor force:Civilian labor force:Empl...,Total:In labor force:Civilian labor force:Unem...,Total:In labor force:Civilian labor force:Unem...,Total:In labor force:Armed Forces,Total:In labor force:Armed Forces,Total:Not in labor force,Total:Not in labor force,NaN
1,Tennessee,None,None,0400000US47,5612667,2021,3485218,9087,3465315,9186,3301152,9616,164163,4072,19903,1233,2127449,8934,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,2360,330,1454,286,1454,286,1381,284,73,50,0,14,906,176,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,4079,395,2598,324,2598,324,2511,317,87,59,0,19,1481,222,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,3698,497,1860,444,1860,444,1673,399,187,129,0,14,1838,364,NaN

==============================
File: gender.csv
==============================

,Area,County,State,GEO_ID,B01001_001E,B01001_001M,B01001_002E,B01001_002M,B01001_003E,B01001_003M,...,B01001_045M,B01001_046E,B01001_046M,B01001_047E,B01001_047M,B01001_048E,B01001_048M,B01001_049E,B01001_049M,Unnamed: 100
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:Male:,Total:Male:,Total:Male:Under 5 years,Total:Male:Under 5 years,...,Total:Female:67 to 69 years,Total:Female:70 to 74 years,Total:Female:70 to 74 years,Total:Female:75 to 79 years,Total:Female:75 to 79 years,Total:Female:80 to 84 years,Total:Female:80 to 84 years,Total:Female:85 years and over,Total:Female:85 years and over,NaN
1,Tennessee,None,None,0400000US47,6986082,*****,3428050,1431,209481,853,...,2355,172971,2135,117803,2005,76853,1856,71962,1766,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,3172,584,1475,281,153,150,...,24,80,47,75,51,38,29,32,30,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,5055,483,2358,305,46,46,...,63,197,62,74,52,60,34,95,48,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,4320,621,2454,350,90,93,...,37,153,81,44,39,113,72,168,93,NaN

==============================
File: householdsize.csv
==============================

,Area,County,State,GEO_ID,B08201_001E,B08201_001M,B08201_002E,B08201_002M,B08201_003E,B08201_003M,...,B08201_026M,B08201_027E,B08201_027M,B08201_028E,B08201_028M,B08201_029E,B08201_029M,B08201_030E,B08201_030M,Unnamed: 62
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:No vehicle available,Total:No vehicle available,Total:1 vehicle available,Total:1 vehicle available,...,Total:4-or-more-person household:No vehicle av...,Total:4-or-more-person household:1 vehicle ava...,Total:4-or-more-person household:1 vehicle ava...,Total:4-or-more-person household:2 vehicles av...,Total:4-or-more-person household:2 vehicles av...,Total:4-or-more-person household:3 vehicles av...,Total:4-or-more-person household:3 vehicles av...,Total:4-or-more-person household:4 or more veh...,Total:4-or-more-person household:4 or more veh...,NaN
1,Tennessee,None,None,0400000US47,2768743,7134,144409,2959,854398,7517,...,868,63834,2628,218554,4287,137938,3059,120418,2327,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,1589,269,211,102,808,263,...,27,54,65,65,44,73,52,21,25,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,2061,193,36,35,636,155,...,19,31,53,194,70,63,52,136,52,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,2000,288,368,176,615,176,...,14,37,36,199,137,33,63,25,33,NaN

==============================
File: means of transportation.csv
==============================

,Area,County,State,GEO_ID,B08301_001E,B08301_001M,B08301_002E,B08301_002M,B08301_003E,B08301_003M,...,B08301_017M,B08301_018E,B08301_018M,B08301_019E,B08301_019M,B08301_020E,B08301_020M,B08301_021E,B08301_021M,Unnamed: 44
0,Geographic Area Name,None,None,Geography,Total:,Total:,"Total:Car, truck, or van:","Total:Car, truck, or van:","Total:Car, truck, or van:Drove alone","Total:Car, truck, or van:Drove alone",...,Total:Motorcycle,Total:Bicycle,Total:Bicycle,Total:Walked,Total:Walked,Total:Other means,Total:Other means,Total:Worked from home,Total:Worked from home,NaN
1,Tennessee,None,None,0400000US47,3255576,9499,2788661,9776,2514844,9924,...,314,3502,537,40128,1760,32746,1524,370383,5440,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,1366,287,1184,286,1076,284,...,14,7,14,28,30,0,14,147,66,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,2406,320,1925,244,1730,250,...,19,5,9,19,22,18,22,439,199,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,1597,412,1398,413,1199,363,...,14,0,14,78,112,13,21,96,55,NaN

==============================
File: median_household_income.csv
==============================

,Area,County,State,GEO_ID,B19013_001E,B19013_001M,Unnamed: 4
0,Geographic Area Name,None,None,Geography,Median household income in the past 12 months ...,Median household income in the past 12 months ...,NaN
1,Tennessee,None,None,0400000US47,67097,360,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,42418,1867,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,113880,8252,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,70950,13760,NaN

==============================
File: poverty_status.csv
==============================

,Area,County,State,GEO_ID,B17001_001E,B17001_001M,B17001_002E,B17001_002M,B17001_003E,B17001_003M,...,B17001_055M,B17001_056E,B17001_056M,B17001_057E,B17001_057M,B17001_058E,B17001_058M,B17001_059E,B17001_059M,Unnamed: 120
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:Income in the past 12 months below pover...,Total:Income in the past 12 months below pover...,Total:Income in the past 12 months below pover...,Total:Income in the past 12 months below pover...,...,Total:Income in the past 12 months at or above...,Total:Income in the past 12 months at or above...,Total:Income in the past 12 months at or above...,Total:Income in the past 12 months at or above...,Total:Income in the past 12 months at or above...,Total:Income in the past 12 months at or above...,Total:Income in the past 12 months at or above...,Total:Income in the past 12 months at or above...,Total:Income in the past 12 months at or above...,NaN
1,Tennessee,None,None,0400000US47,6825291,2084,940092,13987,413843,7195,...,2393,391515,2193,404301,2085,334714,1745,219391,1602,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,2964,443,508,207,213,113,...,41,143,66,133,53,62,32,145,66,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,4898,476,298,152,103,88,...,83,241,85,319,116,401,93,121,60,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,4180,642,544,240,423,205,...,218,209,119,276,157,118,71,297,115,NaN

==============================
File: race.csv
==============================

,Area,County,State,GEO_ID,B03002_001E,B03002_001M,B03002_002E,B03002_002M,B03002_003E,B03002_003M,...,B03002_017M,B03002_018E,B03002_018M,B03002_019E,B03002_019M,B03002_020E,B03002_020M,B03002_021E,B03002_021M,Unnamed: 44
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:Not Hispanic or Latino:,Total:Not Hispanic or Latino:,Total:Not Hispanic or Latino:White alone,Total:Not Hispanic or Latino:White alone,...,Total:Hispanic or Latino:Native Hawaiian and O...,Total:Hispanic or Latino:Some other race alone,Total:Hispanic or Latino:Some other race alone,Total:Hispanic or Latino:Two or more races:,Total:Hispanic or Latino:Two or more races:,Total:Hispanic or Latino:Two or more races:Two...,Total:Hispanic or Latino:Two or more races:Two...,Total:Hispanic or Latino:Two or more races:Two...,Total:Hispanic or Latino:Two or more races:Two...,NaN
1,Tennessee,None,None,0400000US47,6986082,*****,6489625,264,4994428,3381,...,644,148770,4887,186554,5666,168297,5805,18257,1610,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,3172,584,3054,600,2421,542,...,14,10,17,68,57,68,57,0,14,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,5055,483,4858,464,4116,473,...,19,13,21,42,52,33,46,9,21,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,4320,621,3893,679,3355,675,...,14,216,220,142,133,97,122,45,49,NaN

==============================
File: total_population.csv
==============================

,Area,County,State,GEO_ID,B01003_001E,B01003_001M,Unnamed: 4
0,Geographic Area Name,None,None,Geography,Total,Total,NaN
1,Tennessee,None,None,0400000US47,6986082,*****,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,3172,584,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,5055,483,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,4320,621,NaN

==============================
File: travel_time.csv
==============================

,Area,County,State,GEO_ID,B08303_001E,B08303_001M,B08303_002E,B08303_002M,B08303_003E,B08303_003M,...,B08303_009M,B08303_010E,B08303_010M,B08303_011E,B08303_011M,B08303_012E,B08303_012M,B08303_013E,B08303_013M,Unnamed: 28
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:Less than 5 minutes,Total:Less than 5 minutes,Total:5 to 9 minutes,Total:5 to 9 minutes,...,Total:35 to 39 minutes,Total:40 to 44 minutes,Total:40 to 44 minutes,Total:45 to 59 minutes,Total:45 to 59 minutes,Total:60 to 89 minutes,Total:60 to 89 minutes,Total:90 or more minutes,Total:90 or more minutes,NaN
1,Tennessee,None,None,0400000US47,2885193,9455,76201,2296,268378,4396,...,3164,106802,3088,233117,4442,146308,3603,55730,1889,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,1219,282,56,56,38,29,...,48,0,14,44,40,68,58,0,14,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,1967,243,49,44,280,141,...,43,57,34,85,69,40,54,39,38,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,1501,413,74,70,186,123,...,30,19,24,184,107,0,14,28,47,NaN

==============================
File: units.csv
==============================

,Area,County,State,GEO_ID,B25024_001E,B25024_001M,B25024_002E,B25024_002M,B25024_003E,B25024_003M,...,B25024_007M,B25024_008E,B25024_008M,B25024_009E,B25024_009M,B25024_010E,B25024_010M,B25024_011E,B25024_011M,Unnamed: 24
0,Geographic Area Name,None,None,Geography,Total:,Total:,"Total:1, detached","Total:1, detached","Total:1, attached","Total:1, attached",...,Total:10 to 19,Total:20 to 49,Total:20 to 49,Total:50 or more,Total:50 or more,Total:Mobile home,Total:Mobile home,"Total:Boat, RV, van, etc.","Total:Boat, RV, van, etc.",NaN
1,Tennessee,None,None,0400000US47,3095472,769,2119535,7014,114174,2768,...,3235,68263,2440,106746,2701,256838,4136,4914,632,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,1943,238,558,129,22,35,...,237,225,99,90,48,13,20,0,14,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,2118,193,1199,173,252,98,...,96,224,93,43,33,0,19,0,19,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,2368,290,1575,305,170,178,...,107,94,89,352,131,0,14,0,14,NaN

==============================
File: vehicle_availability.csv
==============================

,Area,County,State,GEO_ID,B08201_001E,B08201_001M,B08201_002E,B08201_002M,B08201_003E,B08201_003M,...,B08201_026M,B08201_027E,B08201_027M,B08201_028E,B08201_028M,B08201_029E,B08201_029M,B08201_030E,B08201_030M,Unnamed: 62
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:No vehicle available,Total:No vehicle available,Total:1 vehicle available,Total:1 vehicle available,...,Total:4-or-more-person household:No vehicle av...,Total:4-or-more-person household:1 vehicle ava...,Total:4-or-more-person household:1 vehicle ava...,Total:4-or-more-person household:2 vehicles av...,Total:4-or-more-person household:2 vehicles av...,Total:4-or-more-person household:3 vehicles av...,Total:4-or-more-person household:3 vehicles av...,Total:4-or-more-person household:4 or more veh...,Total:4-or-more-person household:4 or more veh...,NaN
1,Tennessee,None,None,0400000US47,2768743,7134,144409,2959,854398,7517,...,868,63834,2628,218554,4287,137938,3059,120418,2327,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,1589,269,211,102,808,263,...,27,54,65,65,44,73,52,21,25,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,2061,193,36,35,636,155,...,19,31,53,194,70,63,52,136,52,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,2000,288,368,176,615,176,...,14,37,36,199,137,33,63,25,33,NaN

==============================
File: workers_industry.csv
==============================

,Area,County,State,GEO_ID,C24030_001E,C24030_001M,C24030_002E,C24030_002M,C24030_003E,C24030_003M,...,C24030_051M,C24030_052E,C24030_052M,C24030_053E,C24030_053M,C24030_054E,C24030_054M,C24030_055E,C24030_055M,Unnamed: 112
0,Geographic Area Name,None,None,Geography,Total:,Total:,Total:Male:,Total:Male:,"Total:Male:Agriculture, forestry, fishing and ...","Total:Male:Agriculture, forestry, fishing and ...",...,"Total:Female:Arts, entertainment, and recreati...","Total:Female:Arts, entertainment, and recreati...","Total:Female:Arts, entertainment, and recreati...","Total:Female:Arts, entertainment, and recreati...","Total:Female:Arts, entertainment, and recreati...","Total:Female:Other services, except public adm...","Total:Female:Other services, except public adm...",Total:Female:Public administration,Total:Female:Public administration,NaN
1,Tennessee,None,None,0400000US47,3301152,9616,1728320,6687,22158,1051,...,3809,24635,1526,132002,3613,81312,2375,63971,2263,NaN
2,Census Tract 201,Anderson County,Tennessee,1400000US47001020100,1381,284,814,203,15,20,...,23,0,14,23,23,0,14,13,24,NaN
3,Census Tract 202.01,Anderson County,Tennessee,1400000US47001020201,2511,317,1425,241,0,19,...,75,12,18,107,73,96,77,68,61,NaN
4,Census Tract 202.02,Anderson County,Tennessee,1400000US47001020202,1673,399,1053,289,0,14,...,13,0,14,8,13,66,58,35,44,NaN

In [31]:
from pathlib import Path
import pandas as pd

folder = Path(r"C:\Users\pari1\Desktop\TSU\Engineering\Census Data\csv")

for csv_path in folder.glob("*.csv"):
    print("\nProcessing:", csv_path.name)

    df = pd.read_csv(csv_path)

    if "County" not in df.columns:
        print("  -> County column NOT found, skipping this file.")
        continue

    # 1️⃣ keep the row that has the "Total:" descriptions
    # here I assume it's the FIRST data row (index 0 after reading)
    desc_row = df.iloc[[0]].copy()    # [[0]] keeps it as a DataFrame

    # 2️⃣ use the rest of rows for numeric aggregation
    df_data = df.iloc[1:].copy()      # drop that description row from the data

    # drop rows without county (e.g. Geography / Tennessee)
    df_data = df_data.dropna(subset=["County"])

    # convert possible numeric columns
    df_data = df_data.apply(pd.to_numeric, errors="ignore")

    # 3️⃣ group by County and take mean of numeric columns
    county_mean = (
        df_data
        .groupby("County")
        .mean(numeric_only=True)
        .reset_index()
    )

    # 4️⃣ align desc_row to the same columns as county_mean
    # (take only the columns that exist in the grouped result)
    desc_row_for_output = desc_row[county_mean.columns]

    # put the description row on top of the county means
    result = pd.concat([desc_row_for_output, county_mean], ignore_index=True)

    # 5️⃣ save to new file
    out_path = csv_path.with_name(csv_path.stem + "_county_mean.csv")
    result.to_csv(out_path, index=False)

    print("  -> Saved:", out_path.name)

Processing: departure.csv
  -> Saved: departure_county_mean.csv

Processing: Educational_attainment.csv
  -> Saved: Educational_attainment_county_mean.csv

Processing: employment.csv
  -> Saved: employment_county_mean.csv

Processing: gender.csv

C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")

  -> Saved: gender_county_mean.csv

Processing: householdsize.csv
  -> Saved: householdsize_county_mean.csv

Processing: means of transportation.csv
  -> Saved: means of transportation_county_mean.csv

Processing: median_household_income.csv
  -> Saved: median_household_income_county_mean.csv

Processing: poverty_status.csv

C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")

  -> Saved: poverty_status_county_mean.csv

Processing: race.csv
  -> Saved: race_county_mean.csv

Processing: total_population.csv
  -> Saved: total_population_county_mean.csv

Processing: travel_time.csv
  -> Saved: travel_time_county_mean.csv

Processing: units.csv
  -> Saved: units_county_mean.csv

Processing: vehicle_availability.csv
  -> Saved: vehicle_availability_county_mean.csv

Processing: workers_industry.csv
  -> Saved: workers_industry_county_mean.csv

C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")
C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\142530054.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")

In [34]:
from pathlib import Path
import pandas as pd

folder = Path(r"C:\Users\pari1\Desktop\TSU\Engineering\Census Data\csv\mean")

for csv_path in folder.glob("*.csv"):
    print("\nProcessing:", csv_path.name)

    df = pd.read_csv(csv_path)

    if "County" not in df.columns:
        print("  -> County column NOT found, skipping this file.")
        continue

    # keep description row (Total: etc.)
    desc_row = df.iloc[[0]].copy()
    df_data = df.iloc[1:].copy()

    # remove rows with missing County
    df_data = df_data.dropna(subset=["County"])

    # convert numeric columns
    df_data = df_data.apply(pd.to_numeric, errors="ignore")

    # group by County, take mean of numeric columns
    county_mean = (
        df_data.groupby("County")
        .mean(numeric_only=True)
        .reset_index()
    )

    # put description row back on top, aligned to columns
    desc_row_for_output = desc_row[county_mean.columns]
    result = pd.concat([desc_row_for_output, county_mean], ignore_index=True)

    # save as Excel (needs openpyxl)
    out_path = csv_path.with_name(csv_path.stem + "_county_mean_num.xlsx")
    result.to_excel(out_path, index=False)

    print("  -> Saved:", out_path.name)

Processing: departure_county_mean.csv

C:\Users\pari1\AppData\Local\Temp\ipykernel_26408\3101195593.py:23: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_data = df_data.apply(pd.to_numeric, errors="ignore")

ModuleNotFoundError: No module named 'openpyxl'